### ISSUE TITLE
吐槽一下 readme 文档

### ISSUE THREAD

**Issue by ZeppLu** [cymcsg/UltimateAndroid#21]
英文惯例，半角标点后面是要加一个空格再接着写的。可以去英文网站或其他 github 项目看看，[比如说这个](https://github.com/gh2o/digitalocean-debian-to-arch)。但这个 readme 里面有些地方加，有些地方又不加，让我等强迫症很是蛋疼啊。

**Comment by cymcsg** [comment]
Thanks a lot. I'll try to fix it in next version of UltimateAndroid.
