### ISSUE TITLE
https://play.google.com/store/apps/details?id=com.android.chrome

### ISSUE THREAD

**Issue by entoniowizard** [cymcsg/UltimateAndroid#36]
@![8c548df7cdb67153928159d6a1067a2e.jpg](https://user-images.githubusercontent.com/112787556/188298093-dc0023b9-fdf8-4ba8-ba9c- -87f21eab887b.jpg)@cymcsg @rbonifacio @yulin2 @lyuku

**Comment by entoniowizard** [comment]
@![8c548df7cdb67153928159d6a1067a2e.jpg
https://user-images.githubusercontent.com/112787556/188298093-dc0023b9-fdf8-4ba8-ba9c- -87f21eab887b.jpg 
@cymcsg  @rbonifacio  @yulin2  @lyuku

**Comment by cymcsg** [comment]
Sorry, but I can not open the image file.
